/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FindUsRouteImport } from './routes/find-us'
import { Route as GamedayRouteImport } from './routes/gameday'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as TheTribeRouteImport } from './routes/the-tribe'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FindUsRoute = FindUsRouteImport.update({
  id: '/find-us',
  path: '/find-us',
  getParentRoute: () => rootRouteImport,
} as any)
const GamedayRoute = GamedayRouteImport.update({
  id: '/gameday',
  path: '/gameday',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const TheTribeRoute = TheTribeRouteImport.update({
  id: '/the-tribe',
  path: '/the-tribe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/find-us': typeof FindUsRoute
  '/gameday': typeof GamedayRoute
  '/schedule': typeof ScheduleRoute
  '/the-tribe': typeof TheTribeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/find-us': typeof FindUsRoute
  '/gameday': typeof GamedayRoute
  '/schedule': typeof ScheduleRoute
  '/the-tribe': typeof TheTribeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/find-us': typeof FindUsRoute
  '/gameday': typeof GamedayRoute
  '/schedule': typeof ScheduleRoute
  '/the-tribe': typeof TheTribeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/find-us' | '/gameday' | '/schedule' | '/the-tribe'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/find-us' | '/gameday' | '/schedule' | '/the-tribe'
  id: '__root__' | '/' | '/find-us' | '/gameday' | '/schedule' | '/the-tribe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FindUsRoute: typeof FindUsRoute
  GamedayRoute: typeof GamedayRoute
  ScheduleRoute: typeof ScheduleRoute
  TheTribeRoute: typeof TheTribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-us': {
      id: '/find-us'
      path: '/find-us'
      fullPath: '/find-us'
      preLoaderRoute: typeof FindUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gameday': {
      id: '/gameday'
      path: '/gameday'
      fullPath: '/gameday'
      preLoaderRoute: typeof GamedayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/the-tribe': {
      id: '/the-tribe'
      path: '/the-tribe'
      fullPath: '/the-tribe'
      preLoaderRoute: typeof TheTribeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FindUsRoute: FindUsRoute,
  GamedayRoute: GamedayRoute,
  ScheduleRoute: ScheduleRoute,
  TheTribeRoute: TheTribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
